#!/bin/sh

# intro:
#
#   global `<C-x><C-e>` (readline editor / zsh zle)
#
# usage:
#
#   # add to tmux.conf (modify key / path accordingly):
#   bind -n M-e run path-of-this-file

set -e

s=$(mktemp)
tmux popup -E \
    vim -S "$(dirname "$0")"/edit-line.vim -- "$s"

line=$(cat -- "$s")
rm -- "$s"

if [ -n "$line" ]; then
    tmux send -l -- "$line"
fi
