#!/bin/sh
set -e

main()
{
    # We have entered copy-mode before executing this script; so cancel here.
    tmux send-keys -X cancel

    current_x=$1
    current_y=$2
    target_x=$3
    target_y=$4
    pane_width=$5

    offset=$(( (target_y - current_y) * pane_width + (target_x - current_x) ))
    if test "$offset" -eq 0; then exit; fi

    # if all characters are single width, then we can exit here...
    # tmux send -N "${offset#-}" $(
    # if test "$offset" -gt 0; then echo Right; else echo Left; fi
    # )

    # About capturep -N / -T option:
    # It only breaks if end of line are double width characters
    #   and a following non-exist whitespace as placeholder;
    # In other situations, everything works as expected.

    offset_char=$(
    tmux capturep -p -N -T | env \
        CURRENT_X="$current_x" \
        CURRENT_Y="$current_y" \
        TARGET_X="$target_x" \
        TARGET_Y="$target_y" \
        PANE_WIDTH="$pane_width" \
        vim - -S "$(dirname "$0")"/calculate-strlen.vim -es --not-a-term \
        --clean -Nu NONE 2>/dev/null
    )

    # sanity check
    if ! printf %s "$offset_char" | grep -Eq '^[0-9]+$'; then
        offset_char=$offset
    fi
    if test "$offset_char" -eq 0; then exit; fi

    tmux send -N "${offset_char#-}" $(
    if test "$offset" -gt 0; then echo Right; else echo Left; fi
    )
}

main $(
tmux display -p '#{cursor_x} #{cursor_y} #{copy_cursor_x} #{copy_cursor_y} #{pane_width}'
)
