#!/bin/sh

set -e

if command -v gvim >/dev/null; then
    exec gvim -f +KqutebrowserEditCmd
elif command -v tmux >/dev/null; then
    lock=tmux_lock_$(date +%s)
    tmux neww -e "QUTE_FIFO=$QUTE_FIFO" -e "QUTE_COMMANDLINE_TEXT=$QUTE_COMMANDLINE_TEXT" "vim +KqutebrowserEditCmd; tmux wait -S "$lock""
    # TODO activate terminal window
    tmux wait "$lock"
fi
